baseURL = 'http://samuelmurillo.xyz/'
languageCode = 'en-us'
title = 'Samuel Murillo - SRE'
theme = 'archie'
pygmentsstyle = "nord"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=3

[params]
  mode="dark"
  useCDN=true
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  subtitle="Computer Engineer/Site Reliability Engineer"

  # Subtitle for home
  homeSubtitle = "Computer Engineer/Site Reliability Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Computer Engineer/Site Reliability Engineer"
  keywords = "sre, devops, aws, lambda, serverless, terraform, python, chalice"
  images = [""]

  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/SamuelM333"

  [[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/samuel-murillo/"

  [[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:contact@samuelmurillo.xyz"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4