baseURL = "http://samuelmurillo.xyz/"
languageCode = "en-us"
title = "Samuel Murillo - Infra guy"
subtitle = "Some"

theme = "hugo-ficurinia"

author = "Samuel Murillo"
copyright = "Samuel Murillo - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30
enableEmoji = true

[params]
    description = "Samuel Murillo's blog about programming and other cool stuff"
    author = "Samuel Murillo"
    keywords = ["sre", "devops", "aws", "lambda", "serverless", "terraform", "python", "chalice"]
    
    # logo = "/logo.svg"
    logo = ""
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    # svgicon = "/logo.svg"
    svgicon = ""
    icon512 = "/android-chrome-512x512.png"
    imageInArticlePreview = true
    enableShareOnFediverse = false
    enableRelatedArticles = false
    relatedArticlesNum = 2 
    forceRedirect = true
    showRss = false

    enableFeatured = true

    # enableSidebarLayout = true
    # tocInSidebar = true # if the sidebar is enbabled, show the TOC in the sidebar

    # enable analytics using Umami
    # umamiScriptUrl = "https://something.com/..."
    # umamiWebsiteId = "example-tracking-code"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 3
    [[menu.icons]]
        identifier = "github"
        weight = 10
        name = "GitHub"
        icon = "github"
        url = "https://github.com/SamuelM333"
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/samuel-murillo/"
        weight = 20
    [[menu.icons]]
        identifier = "email"
        name = "Email"
        url = "mailto:contact@samuelmurillo.xyz"
        weight = 30
